# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 249681eeb93736aa3db61baced09307cecf05bd4011421a80ed9a61c12aef8f6c1671066e7cc51ea41744ca8a8041d354a2103c08530226cd50aaada774a02d5

test:
  secret_key_base: 5b523f4314039586bc36fd1044ca797ddb359226485f7cdad473713f9f59cf30d793f124415f76e0b75c2a8ced7a15719a1d2b9fe39d50584857e51f99e75d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
