# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf8edc0c8cb37b9d746305ef70d3eaf0d3c12324ce8b96d5359dee97ea11274b46ba81d1848ccba4d2314ab5070ca29dcc5486e65fa3eb8e56bd9f8e663ff303

test:
  secret_key_base: 872f6bab8a44a8a7f46e2b49eaf631e2eae6500132ea01f7bd63454ddaa3c1b4cd5791ff1de03de2af74f9717e41522632d047793b77f515938a8f09a6a90fbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
